import { EnvSchema } from '../types/schema.js';

export function generateEnvExample(schema: EnvSchema): string {
  let example = `# .env.example\n# Auto-generated by env-sentinel\n\n`;

  for (const [key, opt] of Object.entries(schema)) {
    if (opt.description) {
      example += `# ${opt.description}\n`;
    }
    
    let defaultValue = '';
    if (opt.default !== undefined) {
      if (typeof opt.default === 'string' && opt.default.includes(' ')) {
         defaultValue = `"${opt.default}"`;
      } else {
         defaultValue = String(opt.default);
      }
    } else if (opt.example !== undefined) {
      defaultValue = opt.example;
    } else if (opt.required !== false) {
      defaultValue = `your_${key.toLowerCase()}`;
    }

    example += `${key}=${defaultValue}\n\n`;
  }
  
  return example.trim() + '\n';
}
