import { EnvSchema } from '../types/schema.js';

export function generateMarkdownDocs(schema: EnvSchema): string {
  let md = `# Environment Variables Documentation\n\n`;
  md += `| Variable | Type | Required | Default | Description |\n`;
  md += `| :--- | :--- | :--- | :--- | :--- |\n`;

  for (const [key, opt] of Object.entries(schema)) {
    const type = `\`${opt.type}\``;
    const required = opt.required !== false ? '✅' : '❌';
    const defaultValue = opt.default !== undefined ? `\`${JSON.stringify(opt.default)}\`` : '-';
    const description = opt.description || '-';
    
    md += `| **${key}** | ${type} | ${required} | ${defaultValue} | ${description} |\n`;
  }

  md += `\n\n> Auto-generated by [env-sentinel](https://github.com/dotenv-schema)\n`;
  
  return md;
}
